feat: great rewrite of backup-local

diff --git a/backup-local b/backup-local
--- a/backup-local
+++ b/backup-local
@@ -1,179 +1,142 @@
 #!/usr/bin/env bash
 
-# -----------------------------------------------------------------------------
 # Script for backing up data with rsync using Tower of Hanoi rotation method
-# -----------------------------------------------------------------------------
-# Copyright (c) 2023 Steffen Fieger
-#
-# Permission is hereby granted, free of charge, to any person obtaining a copy
-# of this software and associated documentation files (the "Software"), to deal
-# in the Software without restriction, including without limitation the rights
-# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
-# copies of the Software, and to permit persons to whom the Software is
-# furnished to do so, subject to the following conditions:
-#
-# The above copyright notice and this permission notice shall be included in all
-# copies or substantial portions of the Software.
-#
-# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
-# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
-# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
-# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
-# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
-# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
-# SOFTWARE.
-# -----------------------------------------------------------------------------
-# Using the build-template of Dave Jarvis
-# https://dave.autonoma.ca/
-# -----------------------------------------------------------------------------
-source /usr/local/bin/shell-template.sh
 
-SCRIPT_VERSION="1.0.3"
-DATE=$(echo $(date --iso-8601)
+set -Eeuo pipefail
+trap cleanup SIGINT SIGTERM ERR EXIT
 
-ARG_DAY=$(echo $(date +%j) | sed 's/^0*//')
-ARG_MOUNT="/media/backup"
-ARG_TARGET="${ARG_MOUNT}"
+script_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd -P)
 
-DEPENDENCIES=(
-  "rsync,https://rsync.samba.org/"
-)
+usage() {
+  cat <<EOF
+Usage: $(basename "${BASH_SOURCE[0]}") [-h] [-d] [--day value] [--mount value] [--target value] uuid source1 [source2...]
 
-ARGUMENTS+=(
-  "d,day,Day of the year (default: ${ARG_DAY})"
-  "i,uuid,UUID of the backup drive"
-  "m,mount,Mountpoint for backup (default: ${ARG_MOUNT})"
-  "s,sources,Comma seperated list of sources"
-  "t,target,Backup target (default: ${ARG_TARGET})"
-)
+Backs up data from the sources to the with uuid mounted drive.
+Uses the Tower of Hanoi rotation method
 
-# -----------------------------------------------------------------------------
-# Mounting the backup drive
-# -----------------------------------------------------------------------------
-preprocess() {
-  $log "Date: ${DATE}"
-  $log "Mounting ${ARG_UUID} on ${ARG_MOUNT}"
+Available options:
 
-  sudo mount -U "${ARG_UUID}" "${ARG_MOUNT}" > /dev/null 2>&1
-  local -r EXIT_CODE=$?
-
-  if [ ${EXIT_CODE} -ne 0 ]; then
-    error "mount failed with exit code ${EXIT_CODE}."
-
-    return 0
-  fi
-
-  SOURCES="${ARG_SOURCES}"
-  SOURCES=$(echo ${SOURCES} | sed 's/,/ /g')
-
-  $log "Sources: ${SOURCES}"
-  $log "Target : ${ARG_TARGET}"
-
-  return 1
+-h, --help      Print this help and exit
+-d, --debug     Print script debug info
+    --day       The day of the year for determining the output tower
+    --mount     Specifies the mountpount for the backup (default: /media/backup)
+    --target    Specifies the target-folder for the backup (default: /media/backup)
+EOF
+  exit
 }
 
-# -----------------------------------------------------------------------------
-# Perform all commands that the script requires.
-#
-# @return 0 - Indicate to terminate the script with non-zero exit level
-# @return 1 - All tasks completed successfully (default)
-# -----------------------------------------------------------------------------
-execute() {
-  $log "getting Tower of Hanoi (target folder)"
-  target_folder
+cleanup() {
+  trap - SIGINT SIGTERM ERR EXIT
+  sudo umount ${mount} > /dev/null 2>&1
+}
 
-  $log "backing up ${SOURCES} to ${ARG_TARGET}/${TARGET_FOLDER}"
-
-  if [ "${TARGET_FOLDER}" == "f" ]; then
-    sudo sync \
-      --archive \
-      --checksum \
-      --delete \
-      ${SOURCES} "${ARG_TARGET}/${TARGET_FOLDER}"
+setup_colors() {
+  if [[ -t 2 ]] && [[ -z "${NO_COLOR-}" ]] && [[ "${TERM-}" != "dumb" ]]; then
+    NOFORMAT='\033[0m' BLACK='\033[0;30m' RED='\033[0;31m' GREEN='\033[0;32m' YELLOW='\033[0;33m' BLUE='\033[0;34m' MAGENTA='\033[0;35m' CYAN='\033[0;36m' WHITE='\033[1;37m'
   else
+    NOFORMAT='' BLACK='' RED='' GREEN='' YELLOW='' BLUE='' MAGENTA='' CYAN='' WHITE=''
+  fi
+}
+
+msg() {
+  echo >&2 -e "${1-}"
+}
+
+die() {
+  local msg=$1
+  local code=${2-1} # default exit status 1
+  msg "$msg"
+  exit "$code"
+}
+
+parse_params() {
+  day=$(echo $(date +%j) | sed 's/^0*//')
+  mount="/media/backup"
+  target="${mount}"
+
+  while :; do
+    case "${1-}" in
+    -h | --help) usage ;;
+    -d | --debug) set -x ;;
+    --no-color) NO_COLOR=1 ;;
+    --day)
+        day="${2-}"
+        shift
+        ;;
+    --mount)
+        mount="${2-}"
+        shift
+        ;;
+    --target)
+        target="${2-}"
+        shift
+        ;;
+    -?*) die "Unknown option: $1" ;;
+    *) break ;;
+    esac
+    shift
+  done
+
+  args=("$@")
+
+  [[ ${#args[@]} -eq 0 ]] && die "Missing script arguments"
+
+  return 0
+}
+
+parse_params "$@"
+setup_colors
+
+uuid="${args[0]}"
+unset args[0]
+
+msg "Day: ${day}"
+msg "Mounting ${uuid} on ${mount}"
+
+sudo mount -U "${uuid}" "${mount}" > /dev/null 2>&1
+
+if [[ $? -ne 0 ]] ; then
+    die "${RED} mount failed with exit code $?."
+fi
+
+sources="${args[@]}"
+
+msg "Sources: ${sources}"
+msg "Target: ${target}"
+
+mod37=$(((-$day & $day) % 37))
+lookup=(32 0 1 26 2 23 27 0 3 16 24 30 28 11 0 13 4 7 17 0 25 22 31 15 29 10 12 6 0 21 14 9 5 20 8 19 18)
+
+if [[ ${lookup[$mod37]} -eq 0 ]] ; then
+    target_folder="a"
+elif [[ ${lookup[$mod37]} -eq 1 ]] ; then
+    target_folder="b"
+elif [[ ${lookup[$mod37]} -eq 2 ]] ; then
+    target_folder="c"
+elif [[ ${lookup[$mod37]} -eq 3 ]] ; then
+    target_folder="d"
+elif [[ ${lookup[$mod37]} -eq 4 ]] ; then
+    target_folder="e"
+else
+    target_folder="f"
+fi
+
+msg "backing up ${sources} to ${target}/${target_folder}"
+
+if [[ "${target_folder}" -eq "f" ]] ; then
     sudo rsync \
-      --archive \
-      --delete \
-      ${SOURCES} "${ARG_TARGET}/${TARGET_FOLDER}"
-  fi
+        --archive \
+        --checksum \
+        --delete \
+        ${sources} "${target}/${target_folder}"
+else
+    sudo rsync \
+        --archive \
+        --delete \
+        ${sources} "${target}/${target_folder}"
+fi
 
-  $log "Last written: ${ARG_TARGET}/${TARGET_FOLDER}"
-  echo "[$(date)] Last written: ${TARGET_FOLDER}" >> "${ARG_TARGET}"/log.backup
+msg "Last written: ${target}/${target_folder}"
+echo "[$(date)] Last written: ${TARGET_FOLDER}" >> "${ARG_TARGET}"/log.backup
 
-  return 1
-}
-
-# -----------------------------------------------------------------------------
-# Unmounting the NAS
-# -----------------------------------------------------------------------------
-postprocess() {
-  $log "Umnounting ${ARG_MOUNT}"
-
-  sudo umount ${ARG_MOUNT} > /dev/null 2>&1
-  local -r EXIT_CODE=$?
-
-  if [ ${EXIT_CODE} -ne 0 ]; then
-    error "umount failed with exit code ${EXIT_CODE}."
-
-    return 0
-  fi
-
-  return 1
-}
-
-# -----------------------------------------------------------------------------
-# Get the Hanoi-Tower
-# -----------------------------------------------------------------------------
-target_folder() {
-  MOD37=$(((-$ARG_DAY & $ARG_DAY) % 37))
-  LOOKUP=(32 0 1 26 2 23 27 0 3 16 24 30 28 11 0 13 4 7 17 0 25 22 31 15 29 10 12 6 0 21 14 9 5 20 8 19 18)
-
-  if (( ${LOOKUP[$MOD37]} == 0 )); then
-    TARGET_FOLDER="a"
-  elif (( ${LOOKUP[$MOD37]} == 1 )); then
-    TARGET_FOLDER="b"
-  elif (( ${LOOKUP[$MOD37]} == 2 )); then
-    TARGET_FOLDER="c"
-  elif (( ${LOOKUP[$MOD37]} == 3 )); then
-    TARGET_FOLDER="d"
-  elif (( ${LOOKUP[$MOD37]} == 4 )); then
-    TARGET_FOLDER="e"
-  else
-    TARGET_FOLDER="f"
-  fi
-}
-
-# -----------------------------------------------------------------------------
-# Parses a single command-line argument.
-#
-# @return Number of arguments and options parsed.
-# -----------------------------------------------------------------------------
-argument() {
-  local consume=1
-
-  case "$1" in
-    -d|--day)
-      ARG_DAY="$2"
-      consume=2
-    ;;
-    -i|--uuid)
-      ARG_UUID="$2"
-      consume=2
-    ;;
-    -m|--mount)
-      ARG_MOUNT="$2"
-      consume=2
-    ;;
-    -s|--sources)
-      ARG_SOURCES="$2"
-      consume=2
-    ;;
-    -t|--target)
-      ARG_TARGET="$2"
-      consume=2
-  esac
-
-  return ${consume}
-}
-
-main "$@"
+cleanup
